# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-09-15
openapi: 3.1.2
info:
  title: Circular
  version: 0.0.1
paths:
  /bus-location:
    get:
      description: Get the current location for all busses
      operationId: get_bus_location
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: false
                additionalProperties:
                  type: object
                  properties:
                    busStatus:
                      type: string
                      enum: [notCirculating, circulating]
                    position:
                      type: array
                      items:
                        type: integer
                      minItems: 2
                      maxItems: 2
                    timestamp:
                      type: string
                      format: date-time
                    speed:
                      type: number
                    headingTowards:
                      type: number
